// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Aj2o3CaZ-tvazArhu5GAPAgbdaP9vpE',
    appId: '1:269827222664:web:8b1ec43c7d436d4c5e433d',
    messagingSenderId: '269827222664',
    projectId: 'booklist-31ab8',
    authDomain: 'booklist-31ab8.firebaseapp.com',
    storageBucket: 'booklist-31ab8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQAGzkm-wDzeEVn9ycBJSB9Ylm8xwH5zU',
    appId: '1:269827222664:android:a3f37a5597b616d25e433d',
    messagingSenderId: '269827222664',
    projectId: 'booklist-31ab8',
    storageBucket: 'booklist-31ab8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4-tBO6HfI-BDhi7rM39iWyFjW4benroY',
    appId: '1:269827222664:ios:9529a55c65fa00ae5e433d',
    messagingSenderId: '269827222664',
    projectId: 'booklist-31ab8',
    storageBucket: 'booklist-31ab8.firebasestorage.app',
    androidClientId: '269827222664-iesv81tngb57qp98bufev2tnb051boph.apps.googleusercontent.com',
    iosClientId: '269827222664-57err175hc7fstogmdq5h9kgp2iv1nsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.booklistt',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4-tBO6HfI-BDhi7rM39iWyFjW4benroY',
    appId: '1:269827222664:ios:9529a55c65fa00ae5e433d',
    messagingSenderId: '269827222664',
    projectId: 'booklist-31ab8',
    storageBucket: 'booklist-31ab8.firebasestorage.app',
    androidClientId: '269827222664-iesv81tngb57qp98bufev2tnb051boph.apps.googleusercontent.com',
    iosClientId: '269827222664-57err175hc7fstogmdq5h9kgp2iv1nsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.booklistt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Aj2o3CaZ-tvazArhu5GAPAgbdaP9vpE',
    appId: '1:269827222664:web:f169de95f7a9c2df5e433d',
    messagingSenderId: '269827222664',
    projectId: 'booklist-31ab8',
    authDomain: 'booklist-31ab8.firebaseapp.com',
    storageBucket: 'booklist-31ab8.firebasestorage.app',
  );
}
